
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pl6;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int RIGHT_SQBRACKET = 13;
  public static final int SEMICOLON = 2;
  public static final int LEFT_SQBRACKET = 12;
  public static final int PLUS = 3;
  public static final int LEFT_BRACE = 14;
  public static final int SQRT = 8;
  public static final int POW = 7;
  public static final int ID = 23;
  public static final int LEFT_PARENTHESIS = 10;
  public static final int FLOAT = 21;
  public static final int RIGHT_PARENTHESIS = 11;
  public static final int UPLUS = 17;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int MINUS = 4;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 22;
  public static final int RIGHT_BRACE = 15;
  public static final int TIPO_INT = 19;
  public static final int TIPO_FLOAT = 20;
  public static final int UMINUS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "SQRT",
  "ASSIGN",
  "LEFT_PARENTHESIS",
  "RIGHT_PARENTHESIS",
  "LEFT_SQBRACKET",
  "RIGHT_SQBRACKET",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "PRINT",
  "UPLUS",
  "UMINUS",
  "TIPO_INT",
  "TIPO_FLOAT",
  "FLOAT",
  "INTEGER",
  "ID"
  };
}

